#!/bin/bash

#----------------------------------------------------------------------------
: << POD
=head2 sourced

Usage: sourced || die "Must be sourced."

Returns true (0) or false (1) depending on if we have been sourced.

=cut
POD

sourced() { [[ ${FUNCNAME[1]} == 'source' ]]; }

sourced || {
  echo 'tools must only be sourced'
  exit 1
}

#----------------------------------------------------------------------------
: << POD
=head2 warn

Usage: warn "message"

C<warn> will print whatever is sent to it to STDERR.

Equivalent to C<echo 'Message' E<gt>&2>

=cut
POD

warn() {
  local -a msg
  msg=("$@")
  [[ -t 0 ]] || readarray -t -O "${#msg[@]}" msg
  printf '%s\n' "${msg[@]}" >&2
}

#----------------------------------------------------------------------------
: << POD
=head2 die

Usage: die "message"
       die 2 "message"
       someprog || die "message"

C<die> will call C<warn> with "message" and then C<exit 1>.

C<die> returns the most recent return code unless you provide a status code as
the second parameter.

=cut
POD

die() {
  # Grab most recent return code
  local rc=$?

  # Only exit 0 if explicitly used in $@.
  [[ $rc -eq 0 ]] && rc=1

  local int_rx='[[:digit:]]+'

  if [[ $1 =~ ^$int_rx$ ]]; then
    rc=$1
    shift
  fi

  msg=("$@")
  [[ -t 0 ]] || readarray -t -O "${#msg[@]}" msg
  [[ ${#msg[@]} -ne 0 ]] && printf '%s\n' "${msg[@]}" >&2

  exit "${rc:-1}"
}

#----------------------------------------------------------------------------
: << POD
=head2 verbose

Usage: verbose "message"

C<verbose> will check if the environment variable C<VERBOSE> is true, and if not,
silently return with a 0 return code.

Otherwise, C<verbose> will C<warn> the message passed in.

Example:

  verbose 'message to display if VERBOSE=1'

=cut
POD

verbose() {
  ((VERBOSE)) || return 0
  local -a msg
  msg=("$@")
  [[ -t 0 ]] || readarray -t -O "${#msg[@]}" msg
  printf '%s\n' "${msg[@]}" >&2
}

#----------------------------------------------------------------------------
: << POD
=head2 debug

Usage: debug "message"

C<debug> will check if the environment variable C<DEBUG> is true, and if not,
silently return with a 0 return code.

Otherwise, C<debug> will determine the function call stack and C<warn> the
"message" with the stack at the beginning of the line.

Example:

  [somefunc(3):func(99)]: message

=cut
POD

debug() {
  ((DEBUG)) || return 0
  local -a msg
  msg=("$@")
  [[ -t 0 ]] || readarray -t -O "${#msg[@]}" msg

  # Assume if we're called with nothing, then we want at least one empty line
  # is wanted.

  [[ ${#msg[@]} -eq 0 ]] && msg=('')

  local lineno func file trace
  local -a el
  local -i lvl=0

  local interactive='I'
  [[ $- == *i* ]] || interactive='i'

  local loginshell='L'
  shopt -q login_shell || loginshell='l'

  local ignore_bats_rx='bats-exec-test|bats\.[0-9]+\.src'

  while true; do
    caller=$(caller $lvl) || break
    # In some instances, ((lvl++)) is causing errors, so do it old school.
    #((lvl++))
    lvl+=1

    read -r lineno func file <<< "$caller"

    # Ignore bats
    [[ $file =~ $ignore_bats_rx ]] && continue

    file="$(basename "$file"):"
    func+=':'

    [[ $func =~ main:|source: ]] && func=

    prefix=$(printf '[%s%s%03d]' "$file" "$func" "$lineno")
    el+=("$prefix")
  done

  for ((ix = ${#el[@]} - 1; ix >= 0; ix--)); do
    trace+="${el[ix]}"
  done

  printf -v prefix '[%s%s]%s' "$interactive" "$loginshell" "$trace"

  for m in "${msg[@]}"; do
    printf '%s %s\n' "$prefix" "$m" >&2
  done
}

#----------------------------------------------------------------------------
: << POD
=head2 is_executable

Returns 0 for a word that can be executed as a command, otherwise returns 1.

=cut
POD

is_executable() {
  local check
  check=$(type -t "$1") || return 1
  [[ $check != 'file' ]] && return 0
  [[ -x "$(command -v "$1" 2> /dev/null)" ]]
}

#----------------------------------------------------------------------------
: << POD
=head2 string

Returns 0 for a non-empty variable, 1 for an empty variable.

=cut
POD

is_string() { [[ -n $1 ]]; }

#----------------------------------------------------------------------------
: << POD
=head2 char

Returns 0 if the value passed is a single character, otherwise returns 1.

=cut
POD

is_char() { [[ ${#1} -eq 1 ]]; }

#----------------------------------------------------------------------------
: << POD
=head2 integer

Checks that a value is a positive integer (a number without a decimal).

=cut
POD

is_integer() { [[ -n $1 ]] && [[ $1 != *[!0-9]* ]]; }
